[env:feather_esp32s3]
platform = espressif32
board = adafruit_feather_esp32s3
framework = arduino

; Monitor Settings
monitor_speed = 115200
monitor_port = COM23
monitor_rts = 0
monitor_dtr = 0

; Important for ESP32-S3 (USB CDC)
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1

; =============================================
; LIBRARIES (lahat ng kailangan mo)
; =============================================
lib_deps = 
    miguelbalboa/MFRC522                ; RFID RC522
    adafruit/Adafruit Fingerprint Sensor Library   ; AS608 Fingerprint
    bblanchon/ArduinoJson               ; Para sa Supabase JSON
    marcoschwartz/LiquidCrystal_I2C     ; Para sa 16x2 LCD (kung gagamitin mo)